# Generated by Django 5.2.4 on 2026-04-03 15:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABTextExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_\\-\\.]+$')])),
                ('label', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('default_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'A/B эксперимент текста',
                'verbose_name_plural': 'A/B эксперименты текста',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LeadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=24)),
                ('source', models.CharField(choices=[('lead_form', 'Lead form'), ('calculator', 'Calculator'), ('hero_cta', 'Hero CTA')], max_length=24)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StatisticSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='main', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_\\-]+$')])),
                ('title', models.CharField(max_length=180)),
                ('know_title', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Секция статистики',
                'verbose_name_plural': 'Секции статистики',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StatisticLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField(default='https://example.com', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cms.statisticsection')),
            ],
            options={
                'verbose_name': 'Ссылка секции статистики',
                'verbose_name_plural': 'Ссылки секции статистики',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StatisticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=280)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.statisticsection')),
            ],
            options={
                'verbose_name': 'Пункт статистики',
                'verbose_name_plural': 'Пункты статистики',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ABTextVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_\\-]+$')])),
                ('text', models.TextField()),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='cms.abtextexperiment')),
            ],
            options={
                'verbose_name': 'Вариант текста',
                'verbose_name_plural': 'Варианты текста',
                'ordering': ('id',),
                'unique_together': {('experiment', 'code')},
            },
        ),
    ]
