# Generated by Django 5.2.4 on 2026-04-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_seed_initial_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticlink',
            name='url',
            field=models.CharField(default='/', max_length=500),
        ),
    ]
