# Generated by Django 5.2.4 on 2026-04-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_statisticlink_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.CharField(max_length=220)),
                ('result', models.CharField(max_length=260)),
                ('review', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=160)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='abtextexperiment',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Текстовый сниппет', 'verbose_name_plural': 'Текстовые сниппеты'},
        ),
        migrations.AlterModelOptions(
            name='abtextvariant',
            options={'ordering': ('id',), 'verbose_name': 'Вариант текста (резерв)', 'verbose_name_plural': 'Варианты текста (резерв)'},
        ),
    ]
