# Generated by Django 5.2.4 on 2026-04-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_seed_caseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='caseitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/'),
        ),
    ]
