# Generated by Django 5.2.4 on 2026-04-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_remove_caseitem_image_url_caseitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrequest',
            name='telegram_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadrequest',
            name='telegram_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leadrequest',
            name='telegram_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadrequest',
            name='telegram_status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], db_index=True, default='pending', max_length=12),
        ),
    ]
