# Generated by Django 5.2.4 on 2026-04-06 17:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_leadrequest_telegram_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_\\-\\.]+$')])),
                ('title', models.CharField(max_length=220)),
                ('text', models.TextField(blank=True)),
                ('selection', models.CharField(choices=[('single', 'Один ответ'), ('multiple', 'Несколько ответов')], default='single', max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Вопрос калькулятора',
                'verbose_name_plural': 'Вопросы калькулятора',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CalculatorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator('^[a-z0-9_\\-\\.]+$')])),
                ('title', models.CharField(max_length=220)),
                ('description', models.CharField(blank=True, max_length=320)),
                ('price', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cms.calculatorquestion')),
            ],
            options={
                'verbose_name': 'Вариант ответа калькулятора',
                'verbose_name_plural': 'Варианты ответов калькулятора',
                'ordering': ('sort_order', 'id'),
                'unique_together': {('question', 'key')},
            },
        ),
    ]
