# Generated by Django 5.2.4 on 2026-04-09 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_seed_calculator_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatoroption',
            name='key',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_\\-\\.]+$')]),
        ),
        migrations.AlterField(
            model_name='calculatorquestion',
            name='key',
            field=models.CharField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_\\-\\.]+$')]),
        ),
    ]
